const SCOPE_Z_INDEX = 100;
const Z_INDEX_GAP = 100;

export const MARKER_Z_INDEX = SCOPE_Z_INDEX + Z_INDEX_GAP; // 200
export const SELECTED_MARKER_Z_INDEX = MARKER_Z_INDEX + Z_INDEX_GAP; // 300
export const HOVER_MARKER_Z_INDEX = SELECTED_MARKER_Z_INDEX + Z_INDEX_GAP; // 400
export const MAP_SEARCH_BUTTON_Z_INDEX = HOVER_MARKER_Z_INDEX + Z_INDEX_GAP; // 500

const MODAL_Z_INDEX = 10000;

export const IMAGE_DETAIL_MODAL_Z_INDEX = MODAL_Z_INDEX + Z_INDEX_GAP; // 10100
